version: '3'
networks:
  app-tier:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '4036:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: whasapp-api
      MYSQL_USER: ego
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICES_TAGS: dev
      SERVICES_NAME: mysql
    networks:
      - app-tier
  backend:
    depends_on:
      - mysql
    build:
      context: . # Lokasi Dockerfile dan kode aplikasi
      dockerfile: Dockerfile # Nama file Dockerfile
    volumes:
      - .:/app # Mount kode aplikasi dari host ke dalam containe
    ports:
      - '5040:5040'
    networks:
      - app-tier
